package Restaurant.src.my;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

//package my;

import java.awt.BorderLayout;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.Date;
import java.util.Formatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JWindow;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author Connor
 */
public class mainUI extends javax.swing.JFrame {

    //holds employee pin from valid login 
    public static String emp_pin;

    /**
     * Creates new form mainUI
     */
    public mainUI(String _emp_pin) {
        this.emp_pin = _emp_pin;
        initComponents();
        labelOrderNo1.setText(String.valueOf(orderNo));
    }
    
    private void updatePane(String temp) throws BadLocationException{
        StyledDocument doc = paneOrder.getStyledDocument();
        SimpleAttributeSet left = new SimpleAttributeSet();
        StyleConstants.setAlignment(left, StyleConstants.ALIGN_LEFT);
        doc.setParagraphAttributes(0, doc.getLength(), left, false);
        doc.insertString(doc.getLength(), temp+'\n', null);
            }
            
    private void updatePane1(String temp) throws BadLocationException{
        StyledDocument doc = paneOrder1.getStyledDocument();
        SimpleAttributeSet right = new SimpleAttributeSet();
        StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
        doc.setParagraphAttributes(0, doc.getLength(), right, false);
        doc.insertString(doc.getLength(), temp+'\n', null);
            }            
            
        
     
    
    double total = 0;
    String output = null;
    private void updateTotal(double num) throws BadLocationException{
        StyledDocument doc = paneTotal.getStyledDocument();
        SimpleAttributeSet right = new SimpleAttributeSet();
        StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
        doc.setParagraphAttributes(0, doc.getLength(), right, false);
        
        
        total = total + num;
        Formatter formatter = new Formatter();
        formatter.format("%.2f", total);
        output = String.valueOf("$"+formatter);
        paneTotal.setText(null);
        doc.insertString(doc.getLength(), output, null);

    }
    
    private void custRewards(){
    String phone_num = custRePane.showInputDialog( "Provide rewards number:" );
    //custRePane.showMessageDialog(null, "Entered rewards number successfully.");
    ///REPLACE WITH CHECKING IF PHONE NUMBER IS VALID IN DATABASE

    DatabaseUtility dbu = new DatabaseUtility();

    custRePane.showMessageDialog(null, dbu.getCustomer(phone_num));    
    

    System.out.println(phone_num);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DatabaseUtility dbu = new DatabaseUtility();

        mainBtn1 = new javax.swing.JButton();
        mainBtn2 = new javax.swing.JButton();
        mainBtn3 = new javax.swing.JButton();
        mainBtn4 = new javax.swing.JButton();
        mainBtn5 = new javax.swing.JButton();
        mainBtn6 = new javax.swing.JButton();
        mainBtn7 = new javax.swing.JButton();
        mainBtn8 = new javax.swing.JButton();
        mainBtn9 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        paneOrder = new javax.swing.JTextPane();
        labelCashier = new javax.swing.JLabel();
        labelOrderNo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        paneTotal = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        paneOrder1 = new javax.swing.JTextPane();
        resetBtn = new javax.swing.JButton();
        finishBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        completeBtn1 = new javax.swing.JButton();
        labelOrderNo1 = new javax.swing.JLabel();
        custRePane = new javax.swing.JOptionPane();

        jScrollPane4 = new javax.swing.JScrollPane();
        paneNotes = new javax.swing.JTextPane();

        StyledDocument doc = paneTotal.getStyledDocument();
        SimpleAttributeSet right = new SimpleAttributeSet();
        StyleConstants.setAlignment(right, StyleConstants.ALIGN_RIGHT);
        doc.setParagraphAttributes(0, doc.getLength(), right, false);
        try {
            doc.insertString(doc.getLength(), "$0.00", null);
        } catch (BadLocationException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        mainBtn1.setBackground(new java.awt.Color(20, 20, 255));
        mainBtn1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainBtn1.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn1.setText(dbu.getSingleMenuItemDataEntry("001", "name"));
        mainBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtn1ActionPerformed(evt);
            }
        });

        mainBtn2.setBackground(new java.awt.Color(20, 20, 255));
        mainBtn2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainBtn2.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn2.setText(dbu.getSingleMenuItemDataEntry("002", "name"));                                      //change back when bug is fixed
        mainBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtn2ActionPerformed(evt);
            }
        });

        mainBtn3.setBackground(new java.awt.Color(20, 20, 255));
        mainBtn3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainBtn3.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn3.setText(dbu.getSingleMenuItemDataEntry("003", "name"));
        mainBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtn3ActionPerformed(evt);
            }
        });

        mainBtn4.setBackground(new java.awt.Color(20, 20, 255));
        mainBtn4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainBtn4.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn4.setText(dbu.getSingleMenuItemDataEntry("004", "name"));
        mainBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtn4ActionPerformed(evt);
            }
        });

        mainBtn5.setBackground(new java.awt.Color(20, 20, 255));
        mainBtn5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainBtn5.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn5.setText(dbu.getSingleMenuItemDataEntry("005", "name"));
        mainBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtn5ActionPerformed(evt);
            }
        });

        mainBtn6.setBackground(new java.awt.Color(20, 20, 255));
        mainBtn6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainBtn6.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn6.setText(dbu.getSingleMenuItemDataEntry("006", "name"));
        mainBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtn6ActionPerformed(evt);
            }
        });

        mainBtn7.setBackground(new java.awt.Color(20, 20, 255));
        mainBtn7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainBtn7.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn7.setText(dbu.getSingleMenuItemDataEntry("007", "name"));
        mainBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtn7ActionPerformed(evt);
            }
        });

        mainBtn8.setBackground(new java.awt.Color(20, 20, 255));
        mainBtn8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainBtn8.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn8.setText(dbu.getSingleMenuItemDataEntry("008", "name"));
        mainBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtn8ActionPerformed(evt);
            }
        });

        mainBtn9.setBackground(new java.awt.Color(20, 20, 255));
        mainBtn9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mainBtn9.setForeground(new java.awt.Color(255, 255, 255));
        mainBtn9.setText(dbu.getSingleMenuItemDataEntry("009", "name"));
        mainBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainBtn9ActionPerformed(evt);
            }
        });

        paneOrder.setEditable(false);
        jScrollPane1.setViewportView(paneOrder);
        //DatabaseUtility dbu = new DatabaseUtility();

        labelCashier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCashier.setText("Cashier: " + dbu.getEmployeeName(emp_pin));
        labelCashier.setAlignmentX(0.5F);
        

        labelOrderNo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelOrderNo.setText("Order Number:");
        labelOrderNo.setAlignmentX(0.5F);


        paneTotal.setEditable(false);
        jScrollPane2.setViewportView(paneTotal);

        paneOrder1.setEditable(false);
        paneOrder1.setAutoscrolls(false);
        paneOrder1.setMinimumSize(new java.awt.Dimension(74, 400));
        paneOrder1.setPreferredSize(new java.awt.Dimension(74, 70));
        
        jScrollPane3.setViewportView(paneOrder1);

        resetBtn.setBackground(new java.awt.Color(255, 20, 20));
        resetBtn.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        resetBtn.setForeground(new java.awt.Color(255, 255, 255));
        resetBtn.setText("Reset Order");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });

        finishBtn.setBackground(new java.awt.Color(255, 20, 20));
        finishBtn.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        finishBtn.setForeground(new java.awt.Color(255, 255, 255));
        finishBtn.setText("Finish Order");
        finishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishBtnActionPerformed(evt);
            }
        });

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        completeBtn1.setBackground(new java.awt.Color(255, 20, 20));
        completeBtn1.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        completeBtn1.setForeground(new java.awt.Color(255, 255, 255));
        completeBtn1.setText("Rewards");
        completeBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeBtn1ActionPerformed(evt);
            }
        });

        labelOrderNo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jScrollPane4.setViewportView(paneNotes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(mainBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(mainBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(mainBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(mainBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(mainBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(mainBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(completeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(finishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(custRePane, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelOrderNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelCashier, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(440, 440, 440)
                        .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCashier, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrderNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelOrderNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mainBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mainBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mainBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(resetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(finishBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(completeBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(custRePane, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void mainBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtn1ActionPerformed
        try {
            //item 001
            DatabaseUtility dbu = new DatabaseUtility();
            updatePane(dbu.getSingleMenuItemDataEntry("001", "name"));          //name as a String 
            updatePane1("$" + dbu.getSingleMenuItemDataEntry("001", "price"));  //$ + price as a String
            updateTotal(dbu.getSingleMenuItemPrice("001"));                                //price as a double
        } catch (BadLocationException ex) {
            Logger.getLogger(mainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mainBtn1ActionPerformed

    private void mainBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtn2ActionPerformed


        try {
            DatabaseUtility dbu = new DatabaseUtility();
            updatePane(dbu.getSingleMenuItemDataEntry("002", "name"));
            updatePane1("$" + dbu.getSingleMenuItemDataEntry("002", "price"));
            updateTotal(dbu.getSingleMenuItemPrice("002"));
        } catch (BadLocationException ex) {
            Logger.getLogger(mainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mainBtn2ActionPerformed

    private void mainBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtn3ActionPerformed
        try {
            //item 003
            DatabaseUtility dbu = new DatabaseUtility();
            updatePane(dbu.getSingleMenuItemDataEntry("003", "name"));
            updatePane1("$" + dbu.getSingleMenuItemDataEntry("003", "price"));
            updateTotal(dbu.getSingleMenuItemPrice("003"));
        } catch (BadLocationException ex) {
            Logger.getLogger(mainUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_mainBtn3ActionPerformed

    private void mainBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainBtn4ActionPerformed
        try {
            //item 004
            DatabaseUtility dbu = new DatabaseUtility();
            updatePane(dbu.getSingleMenuItemDataEntry("004", "name"));
            updatePane1("$" + dbu.getSingleMenuItemDataEntry("004", "price"));
            updateTotal(dbu.getSingleMenuItemPrice("004"));
        } catch (BadLocationException ex) {
            Logger.getLogger(mainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mainBtn4ActionPerformed

    private void mainBtn5ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            //item 005
            DatabaseUtility dbu = new DatabaseUtility();
            updatePane(dbu.getSingleMenuItemDataEntry("005", "name"));
            updatePane1("$" + dbu.getSingleMenuItemDataEntry("005", "price"));
            updateTotal(dbu.getSingleMenuItemPrice("005"));
        } catch (BadLocationException ex) {
            Logger.getLogger(mainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mainBtn5ActionPerformed

    private void mainBtn6ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            //item 006
            DatabaseUtility dbu = new DatabaseUtility();
            updatePane(dbu.getSingleMenuItemDataEntry("006", "name"));
            updatePane1("$" + dbu.getSingleMenuItemDataEntry("006", "price"));
            updateTotal(dbu.getSingleMenuItemPrice("006"));
        } catch (BadLocationException ex) {
            Logger.getLogger(mainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mainBtn6ActionPerformed

    private void mainBtn7ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            //item 007
            DatabaseUtility dbu = new DatabaseUtility();
            updatePane(dbu.getSingleMenuItemDataEntry("007", "name"));
            updatePane1("$" + dbu.getSingleMenuItemDataEntry("007", "price"));
            updateTotal(dbu.getSingleMenuItemPrice("007"));
        } catch (BadLocationException ex) {
            Logger.getLogger(mainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mainBtn7ActionPerformed

    private void mainBtn8ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            //item 008
            DatabaseUtility dbu = new DatabaseUtility();
            updatePane(dbu.getSingleMenuItemDataEntry("008", "name"));
            updatePane1("$" + dbu.getSingleMenuItemDataEntry("008", "price"));
            updateTotal(dbu.getSingleMenuItemPrice("008"));
        } catch (BadLocationException ex) {
            Logger.getLogger(mainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mainBtn8ActionPerformed

    private void mainBtn9ActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            //item 009
            DatabaseUtility dbu = new DatabaseUtility();
            updatePane(dbu.getSingleMenuItemDataEntry("009", "name"));
            updatePane1("$" + dbu.getSingleMenuItemDataEntry("009", "price"));
            updateTotal(dbu.getSingleMenuItemPrice("009"));
        } catch (BadLocationException ex) {
            Logger.getLogger(mainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mainBtn9ActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        paneTotal.setText("$0.00");
        paneOrder.setText(null);
        paneOrder1.setText(null);
        total = 0;
        paneNotes.setText(null);
    }//GEN-LAST:event_resetBtnActionPerformed
    
    int orderNo = 1;
    private void finishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishBtnActionPerformed
        total = 0;
        Date date = new Date();
        SimpleDateFormat formatterForDB = new SimpleDateFormat("yyyy-MM-dd"); 
        //System.out.println(formatterForDB.format(date)); 

        
        try {
           
            String[] arryItems = (paneOrder.getText(0, paneOrder.getStyledDocument().getLength())).split("\n");
            String[] arryPrice = (paneOrder1.getText(0, paneOrder1.getStyledDocument().getLength())).replace("$", "").split("\n");
            
            DatabaseUtility dbu = new DatabaseUtility();
            int dbNo = dbu.getNewOrderNum(orderNo); 

            //send order to the DB 
                //needs: all item name (will be converted to item_num)
                //       all prices (will be totaled into one double)
                //       date: may need to create it in the fx as format is differnt for reciepts
                //       notes
                //       cashier pin
                //       rewards_phone number       CANNOT ADD IN CURRENT CONFIGURATION
                //       ticket number == orderNo in this file
                //       order number  == dbNo in this file

            dbu.insertOrderInDB(arryItems, arryPrice, formatterForDB.format(date), paneNotes.getText(), emp_pin, orderNo, dbNo);


            ////////////////CUSTOMER RECEIPT ITEMS
            //orderNo in this file is actually the ticket number. order number will be generated in the DB utility file
            PrintUtility pu = new PrintUtility(arryItems, arryPrice, date, orderNo, dbNo, paneNotes.getText());
            pu.printCustomerReceipt();

            ////////////////KITCHEN RECEIPT ITEMS
            pu.printKitchenTicket();

            //testing fx of get all item num fx
            //System.out.println(dbu.getListOfItemNum(arryItems));

            //testing date   

            System.out.println( );

            //reset mainUi for next Order
            orderNo += 1;
            paneTotal.setText("$0.00");
            paneOrder.setText(null);
            paneOrder1.setText(null);
            labelOrderNo1.setText(String.valueOf(orderNo));
            paneNotes.setText(null);

            //orderNo += 1;

            //reset order num if order reaches 100
            if (orderNo > 100){
                orderNo = 1;
            }
             
        } catch (BadLocationException ex) {
            Logger.getLogger(mainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_finishBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        super.dispose();
        loginUI Info = new loginUI();
        Info.setTitle("Login");
        Info.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void completeBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeBtn1ActionPerformed
        custRewards();
    }//GEN-LAST:event_completeBtn1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainUI(emp_pin).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completeBtn1;
    private javax.swing.JOptionPane custRePane;
    private javax.swing.JButton finishBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;

    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelCashier;
    private javax.swing.JLabel labelOrderNo;
    private javax.swing.JLabel labelOrderNo1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JButton mainBtn1;
    private javax.swing.JButton mainBtn2;
    private javax.swing.JButton mainBtn3;
    private javax.swing.JButton mainBtn4;
    private javax.swing.JButton mainBtn5;
    private javax.swing.JButton mainBtn6;
    private javax.swing.JButton mainBtn7;
    private javax.swing.JButton mainBtn8;
    private javax.swing.JButton mainBtn9;
    private javax.swing.JTextPane paneNotes;
    private javax.swing.JTextPane paneOrder;
    private javax.swing.JTextPane paneOrder1;
    private javax.swing.JTextPane paneTotal;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
}
